//var file = '';
//file = {
//	"m7688408067":[
//		{
//			"editor":1,
//			"attribute":"words",
//			"dom":""
//		}
//	],
//	"m2642747600":[	
//		{
//			"editor":0,
//			"attribute":"table",
//			"dom":""
//		}
//	],
//	"m2653733876":[
//		{
//			"editor":0,
//			"attribute":"table",
//			"dom":""
//		}
//	],
//	"m9024364451":[
//		{
//			"editor":1,
//			"attribute":"canvas",
//			"dom":""
//		},
//		{
//			"editor":1,
//			"attribute":"table",
//			"dom":""
//		}
//	],
//	"m7968168882":[
//		{
//			"editor":1,
//			"attribute":"canvas",
//			"dom":""
//		},
//		{
//			"editor":1,
//			"attribute":"table",
//			"dom":""
//		}
//	],
//	"m5100815816":[
//		{
//			"editor":1,
//			"attribute":"canvas",
//			"dom":""
//		}
//	],
//	"m5630845076":[
//		{
//			"editor":1,
//			"attribute":"table",
//			"dom":""
//		}
//	],
//	"m7061986575":[
//		{
//			"editor":1,
//			"attribute":"table",
//			"dom":""
//		}
//	],
//	"m3523550800":[
//		{
//			"editor":1,
//			"attribute":"canvas",
//			"dom":""
//		},
//		{
//			"editor":1,
//			"attribute":"words",
//			"dom":""
//		},
//		{
//			"editor":1,
//			"attribute":"canvas",
//			"dom":""
//		},
//		{
//			"editor":1,
//			"attribute":"words",
//			"dom":""
//		}
//	],
//	"m8160920226":[
//		{
//			"editor":1,
//			"attribute":"canvas",
//			"dom":""
//		},
//		{
//			"editor":1,
//			"attribute":"table",
//			"dom":""
//		}
//	],
////	"m4435355568":[
////		{	
////			"editor":1,
////			"attribute":"wordss",
////			"dom":"<div style='background:red;width:100px;height:100px'>111111111111111111111</div>"
////		}
////	],
//	"m4167270559":[
//		{
//			"editor":1,
//			"attribute":"table",
//			"dom":""
//		},
//		{
//			"editor":1,
//			"attribute":"table",
//			"dom":""
//		},
//		{
//			"editor":1,
//			"attribute":"table",
//			"dom":""
//		},
//		{
//			"editor":1,
//			"attribute":"table",
//			"dom":""
//		}
//	],
//	"m9199377344":[
//		{
//			"editor":1,
//			"attribute":"table",
//			"dom":""
//		}
//	],
//	"m1974624892":[
//		{
//			"editor":1,
//			"attribute":"table",
//			"dom":""
//		}
//	],
//	"m141651166":[
//		{
//			"editor":1,
//			"attribute":"words",
//			"dom":""
//		}
//	],
//	"m833134113":[
//		{
//			"editor":1,
//			"attribute":"table",
//			"dom":""
//		},
//		{
//			"editor":1,
//			"attribute":"canvas",
//			"dom":""
//		},
//	],
//	"m6206082188":[
//		{
//			"editor":1,
//			"attribute":"canvas",
//			"dom":""
//		}
//	],
//	"m912698679":[
//		{
//			"editor":1,
//			"attribute":"canvas",
//			"dom":""
//		}
//	],
//	"m5966234340":[
//		{
//			"editor":1,
//			"attribute":"canvas",
//			"dom":""
//		}
//	],
//	"m7311084512":[
//		{
//			"editor":1,
//			"attribute":"canvas",
//			"dom":""
//		}
//	],
//	"m1633115306":[
//		{
//			"editor":1,
//			"attribute":"canvas",
//			"dom":""
//		}
//	],
//	"m2405266557":[
//		{
//			"editor":1,
//			"attribute":"words",
//			"dom":""
//		}
//	],
//	"m725808891":[
//		{
//			"editor":1,
//			"attribute":"words",
//			"dom":""
//		}
//	],
//	"m7797298241":[
//		{
//			"editor":1,
//			"attribute":"canvas",
//			"dom":""
//		},
//		{
//			"editor":1,
//			"attribute":"table",
//			"dom":""
//		},
//		{
//			"editor":1,
//			"attribute":"table",
//			"dom":""
//		}
//	],
//	"m3737948765":[
//		{
//			"editor":1,
//			"attribute":"table",
//			"dom":""
//		}
//	],
//	"m1797073735":[
//		{
//			"editor":1,
//			"attribute":"empty",
//			"dom":""
//		}
//	],
//	"m4974419579":[
//		{
//			"editor":1,
//			"attribute":"empty",
//			"dom":"暂无数据"
//		}
//	],
//	"m2137969819":[
//		{
//			"editor":1,
//			"attribute":"empty",
//			"dom":""
//		}
//	],
//	"m3597370042":[
//		{
//			"editor":1,
//			"attribute":"words",
//			"dom":""
//		}
//	],
//	"m7156231092":[
//		{
//			"editor":1,
//			"attribute":"table",
//			"dom":""
//		}
//	],
//	"m9558332368":[
//		{
//			"editor":1,
//			"attribute":"canvas",
//			"dom":""
//		}
//	],
//	"m2286317098":[
//		{
//			"editor":1,
//			"attribute":"canvas",
//			"dom":""
//		}
//	],
//	"m346237126":[
//		{
//			"editor":1,
//			"attribute":"empty",
//			"dom":""
//		}
//	],
//	"m2559296431":[
//		{
//			"editor":1,
//			"attribute":"empty",
//			"dom":""
//		}
//	],
//	"m1417396287":[
//		{
//			"editor":1,
//			"attribute":"canvas",
//			"dom":"暂无数据"
//		},
//		{
//			"editor":1,
//			"attribute":"canvas",
//			"dom":"暂无数据"
//		}
//	],
//	"m4958752961":[
//		{
//			"editor":1,
//			"attribute":"canvas",
//			"dom":""
//		}
//	],
//	"m4905685123":[
//		{
//			"editor":1,
//			"attribute":"canvas",
//			"dom":""
//		}
//	],
//	"m567070645":[
//		{
//			"editor":1,
//			"attribute":"table",
//			"dom":""
//		}
//	],
//	"m2349038176":[
//		{
//			"editor":1,
//			"attribute":"words",
//			"dom":""
//		}
//	]
//}
//
//
////$(function(){
//	//console.log(file)
//// 	var keys1=[];
////  for (var p1 in file) {
////	  if (file.hasOwnProperty(p1)){
////	       keys1.push(p1);
////		}
////	}
//// keys1.push(key);
////console.log(keys1[0]);
////	var doms=[];
////	var html1="2222"
////	console.log(html1)
////  for(var key in file){
////  	$(file[key]).each(function(item,value){
////  		var dom=value.dom;
////  		console.log(value.dom);
//    		//doms.push(value.dom)
//    		//doms[0]=html1
////    		console.log(doms[0])
////  	})
////		file[key].splice(1,1);
////		var jsonarray=file[key];
////		console.log(jsonarray);
////		var jsonarray = eval(file[key]);
////		var arr  =
////		{
////			"editor":1,
////			"attribute":"words",
////			"dom":"2222"
////		}
////		jsonarray.push(arr);
////  }
//  //console.log("doms0:"+doms[0]);
//  
////})
//
